version: '3.3'
services:
  api-sports:
    container_name: api-sports
    image: node:16-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm run start
    ports:
      - '3001:3001'
    env_file:
      - ./.env